## RSA - The Project

Name:  Jonathan Hu

Moodle Email: johu5262@colorado.edu

Name your file "cuidentikey".ipynb  This means YOUR identikey. 

**Do NOT delete instructions or pre-existing comments in the code.** 


<hr />

# Table of Contents/Grading

### 0. Overall structure, code comments, and following directions. (5 points)

### 1. Introduction  (5 points)

### 2. RSA Code Package    (10 points)
###### &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2.1 Basic tool set
###### &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2.2 First tool set
###### &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2.3 Second tool set

### 3. RSA More Code  (10 points)

###### &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  Encode
###### &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  Decode

### 4. Create a demo of encoding and decoding a message that highlights how your code works and the steps involved.   (10 points)

### 5. Results of exchanging codes with others.  (5 points)

### 6. Narrative (25 points)

### 7. Why FME?  (5 points)

### 8. How to break codes  (5 points)

### 9. Code breaking complete examples  (5 points)

### 10. Custom code feature / Advanced options  (15 points) 








### 1. Introduction to your RSA Package and Project.  Give an overview of your project and what you have learned. 

Write an introduction/overview here. This should be something someone who has never seen your project could read to understand what is coming. 


### 2.1
#### Basic tool set

These are functions that you'll need to pre-process the messages before the messages are encoded and decoded by the RSA algorithm. That is the reason we will be defining them first.



In [12]:
def Convert_Text(_string):
    """
    Define this function such that it takes in a simple 
    string such as "hello" and outputs the corresponding
    standard list of integers (ascii) for each letter in the word hello.
    For example:
    _string = hello
    integer_list = [104, 101, 108, 108, 111]
    
    You may use "ord()"
    """
    integer_list = [ord(char) for char in _string]
    return integer_list

In [13]:
def Convert_Num(_list):
    """
    Do the opposite of what you did in the Convert_Text
    function defined above.
    
    Define this function such that it takes in a list of integers
    and outputs the corresponding string (ascii).
    
    For example:
    _list = [104, 101, 108, 108, 111]
    _string = hello
    """
    # Initialize an empty string to store the result
    output_string = ""

    # Iterate through each integer in the list
    for integer in _list:
        # Convert the integer to its corresponding ASCII character and append to the string
        output_string += chr(integer)

    # Return the final string
    return output_string


In [14]:
def Convert_Binary_String(_int):
    """
    Here, you need to define a function that converts an integer to
    a string of its binary expansion.
    
    For example:
    _int = 345
    bits = 101011001
    """
    bits = bin(_int)[2:]
    return bits

Now that you're done with the basic toolset we'll move on to the first tool set which is actually involved in the RSA system.

### 2.2 
#### First tool set.



In [15]:
def FME(base, exponent, modulus):
    """
    1. Using the fast modular exponentiation algorithm,
    the below function should return b**n mod m.
    As described on page 254. (however, you may input the exponent and 
    then convert it to a string - the book verison imports the binary expansion)  
    2. You should use the function defined above Convert_Binary_String() if using the book algorithm.
    3. For this block you MUST use one of the 3 methods offered in the Mastery Workbook.
    4. Any method using bit-shifting or copied from the internet (even changing varibale names) will result in a 0.
    5. **If you are completely stuck, you may use pow() with a 10pt penalty.**

    You may use the function you developed in your Mastery Workbook - but be sure it is your own
    work, commented, etc. and change inputs as needed.
    """  
    result = 1
    # Ensure base is within the modulus
    base = base % modulus  
    while exponent > 0:
        # If exponent is odd, multiply result with base
        if exponent % 2 == 1:
            result = (result * base) % modulus

        # Now exponent is even, divide it by 2
        exponent //= 2
        base = (base * base) % modulus

    return result

In [16]:
def Euclidean_Alg(a, b):
    """
    1. Calculate the Greatest Common Divisor of a and b.
    
    2. This version should have only postive inputs and outputs.
    
    3. The function must return a single integer ('x') which is
    the gcd of a and b.
    
    
    """
    # Ensure a is greater than or equal to b
    if b > a:
        a, b = b, a
    
    while b != 0:
        a, b = b, a % b
    
    # The GCD is the absolute value of a
    return abs(a)

### 2.3
#### Second tool set

Here we will implement the core of the RSA cryptosystem. The functions below will generate the public and private key pairs which will then be used to create a ciphertext using the public key and then decode the same using the pirvate key.



In [17]:
def Find_Public_Key_e(p, q):
    """
    Implement this function such that
    it takes 2 primes p and q.
    
    Use the gcd function that you have 
    defined before.
    
    The function should return 2 elements as follows:
    public key: n
    public key: e
    
    HINT: this function will run a loop to find e such 
    that e is relatively prime to (p - 1) (q - 1) 
    and not equal to p or q.
    
    NOTE: There are a number of ways to implement this key feature. 
    You, as the coder, can choose to how to acheive this goal.
    
    """
    n = p * q
    rprime = (p - 1) * (q - 1)  

    e = 2  
    while e < rprime:
        if Euclidean_Alg(e, rprime) == 1:
            break
        e += 1

    return n, e


In [18]:
def Find_Private_Key_d(e, p, q):
    """
    Implement this function to find the decryption exponent d, 
    such that d is the modular inverse of e. 
    
    This will use the Extended Euclidean Algorithm
    
    This function should return the following:
    d: the decryption component.
    
    This is not a single action, and there are multiple methods to create this. 
    
    You may create a helper function or have all code within this function.
    
    Plan ahead before coding this.

    """
    def extended_gcd(a, b):
        """
        Helper function to calculate the extended GCD.
        """
        if a == 0:
            return b, 0, 1
        else:
            g, x, y = extended_gcd(b % a, a)
            return g, y - (b // a) * x, x

    # Calculate n
    n = p * q

    rprime = (p - 1) * (q - 1)

    _, x, _ = extended_gcd(e, rprime)

    # Ensure 'd' is positive
    d = x % rprime

    return d

### 3.
#### Putting things all together.

1. In this part, you will define two functions `Encode` and `Decode` which will use the public and private keys that you calculated using the above 2 functions in the second toolset.
2. Using the public key, the `Encode` function will encode a message and generate the corresponding cipher_text.
3. Using the private key, the `Decode` function will decode a ciper_text and recover the original message.



In [19]:
def Encode(n, e, message):
    """
    Here, the message will be a string of characters.
    Use the function Convert_Text from 
    the basic tool set and get a list of numbers.
    
    Encode each of these numbers using n and e and
    return the encoded cipher_text.
    """
    # Convert the message to a list of integers using Convert_Text
    integer_list = Convert_Text(message)
    
    # Encode each number using the public key (n, e)
    cipher_text = [pow(num, e, n) for num in integer_list]
    
    return cipher_text

In [20]:
def Decode(n, d, cipher_text):
    """
    Here, the cipher_text will be a list of integers.
    First, you will decrypt each of those integers using 
    n and d.
    
    Later, you will need to use the function Convert_Num from the 
    basic toolset to recover the original message as a string. 
    
    """
    # Decrypt each number using the private key (n, d)
    decrypted_numbers = [pow(num, d, n) for num in cipher_text]
    
    # Convert the list of decrypted integers back to the original message
    original_message = Convert_Num(decrypted_numbers)
    
    return original_message

# ---------------------------------------------------------------------------------------------------------------------------

### 4.  Create a Demo 
This is a **step-by-step** guide to using your code with a specific example that we can follow using the functions you have created above in a mix of code and text blocks. 

**This is essentially a test that demonstates that your code works and how it works. You will call the functions above. You are not using a main function or custom feature here - just calling the functions.**

Imagine you are showing me how you code works in person. 
Your function calls show how it works with an example.
You text s what you would say to me.

It is mix of code blocks and **text blocks** and must discuss all three parts of the project for full credit. You must **show and explain your method and demonstrate (by calling your function as an example.** for generating keys and how your encoding and decoding functions work. 


* Generate keys. 

* Encode a message.

* Decode the same message. 


## Generate Keys

In [21]:
# The Find_Public_Key_e function is used to generate the public key, and the Find_Private_Key_d function is used to generate the private key.
p = 181
q = 97
public_key = Find_Public_Key_e(p, q)
private_key = Find_Private_Key_d(public_key[1], p, q)

print(f"Prime Numbers: p = {p}, q = {q}")
print(f"Public Key (n, e): {public_key}")
print(f"Private Key (d): {private_key}")

Prime Numbers: p = 181, q = 97
Public Key (n, e): (17557, 7)
Private Key (d): 12343


## Encoding a message

In [22]:
message_to_encode = "What is your favorite instrument?"
encoded_message = Encode(public_key[0], public_key[1], message_to_encode)

print(f"Message to Encode: {message_to_encode}")
print(f"Encoded Message: {encoded_message}")

Message to Encode: What is your favorite instrument?
Encoded Message: [6229, 16018, 14938, 3547, 4645, 7578, 6860, 4645, 13925, 16893, 9437, 12571, 4645, 5084, 14938, 1756, 16893, 12571, 7578, 3547, 6296, 4645, 7578, 14834, 6860, 3547, 12571, 9437, 6895, 6296, 14834, 3547, 6932]


## Decoding

In [23]:
# We use the Public Key and Private Key "n" values as inputs
cipher_text_str = "6229, 16018, 14938, 3547, 4645, 7578, 6860, 4645, 13925, 16893, 9437, 12571, 4645, 5084, 14938, 1756, 16893, 12571, 7578, 3547, 6296, 4645, 7578, 14834, 6860, 3547, 12571, 9437, 6895, 6296, 14834, 3547, 6932"
# Convert the string to a list of integers
cipher_text = [int(num) for num in cipher_text_str.split(', ')]

decoded_message = Decode(public_key[0], private_key, cipher_text)
print(f"Decoded Message: {decoded_message}")

Decoded Message: What is your favorite instrument?


# ---------------------------------------------------------------------------------------------------------------------------

### 5. Code Exchange
Now that your code is working and you are able read and write message, include 3 complete examples of exhanging code from Piazza here. Put BOTH the code and solutions here. 

### Post By Professor Stade

In [24]:
# Manually set public and private keys
n = 5251
e = 3
d = 3403

print(f"Public Key (n, e): ({n}, {e})")
print(f"Private Key (d): {d}")

Public Key (n, e): (5251, 3)
Private Key (d): 3403


In [25]:
# Decoding
cipher_text_str = "2128, 1150, 4250, 1349, 1262, 3336, 2371, 2497, 519, 1262, 1263, 1105, 3336, 1349, 1262, 2310, 1105, 3336, 4115, 762, 2405, 1263, 1105, 3336, 1262, 1349, 1150, 1105, 1262, 506, 1105, 1105, 4723, 2405, 2497, 519, 1262, 1974, 2371, 58, 1262, 519, 1105, 1349, 1262, 4839, 1150, 1105, 2497, 1262, 1974, 2371, 58, 762, 1262, 13, 4679, 1573, 1262, 4115, 2371, 2310, 1105, 1262, 2405, 3336, 1262, 4839, 2371, 762, 1560, 2405, 2497, 519, 3250"
# Convert the string to a list of integers
cipher_text = [int(num) for num in cipher_text_str.split(', ')]

decoded_message = Decode(n, d, cipher_text)
print(f"Decoded Message: {decoded_message}")

Decoded Message: What song best describes the feeling you get when your RSA code is working?


In [26]:
# Encoding a message
message_to_encode = "I Don't Daydream Anymore by Unlike Pluto. Probably my go to relaxation song"
encoded_message = Encode(public_key[0], public_key[1], message_to_encode)

print(f"Message to Encode: {message_to_encode}")
print(f"Encoded Message: {encoded_message}")

Message to Encode: I Don't Daydream Anymore by Unlike Pluto. Probably my go to relaxation song
Encoded Message: [43, 4645, 15968, 16893, 14834, 16895, 3547, 4645, 15968, 14938, 13925, 5485, 12571, 6296, 14938, 6895, 4645, 10390, 14834, 13925, 6895, 16893, 12571, 6296, 4645, 1747, 13925, 4645, 13766, 14834, 5206, 7578, 755, 6296, 4645, 39, 5206, 9437, 3547, 16893, 418, 4645, 39, 12571, 16893, 1747, 14938, 1747, 5206, 13925, 4645, 6895, 13925, 4645, 4553, 16893, 4645, 3547, 16893, 4645, 12571, 6296, 5206, 14938, 10405, 14938, 3547, 7578, 16893, 14834, 4645, 6860, 16893, 14834, 4553]


# ---------------------------------------------------------------------------------------------------------------------------

### Post by Derek Larson

In [27]:
# Manually set public and private keys
n = 1649
e = 115
d = 187

print(f"Public Key (n, e): ({n}, {e})")
print(f"Private Key (d): {d}")

Public Key (n, e): (1649, 115)
Private Key (d): 187


In [28]:
# Decoding
cipher_text_str = "155, 203, 1095, 23, 497, 825, 497, 203, 203, 825, 27, 1105, 825, 1095, 1096, 27, 497, 825, 1095, 1096, 27, 716, 188, 825, 1530, 1154, 317, 890, 497, 1507, 825, 1147, 1096, 776, 1095, 23, 497, 825, 722, 1154, 536, 317, 825, 1105, 776, 815, 1154, 317, 27, 1095, 203, 825, 1476, 27, 571, 571, 776, 825, 1095, 1154, 1476, 1476, 27, 716, 188, 504"
# Convert the string to a list of integers
cipher_text = [int(num) for num in cipher_text_str.split(', ')]

decoded_message = Decode(n, d, cipher_text)
print(f"Decoded Message: {decoded_message}")

Decoded Message: Let's see if this thing works. What's your favorite pizza topping?


In [29]:
# Encoding a message
message_to_encode = "Pepperoni"
encoded_message = Encode(n, e, message_to_encode)

print(f"Message to Encode: {message_to_encode}")
print(f"Encoded Message: {encoded_message}")

Message to Encode: Pepperoni
Encoded Message: [1235, 203, 1476, 1476, 203, 317, 1154, 716, 27]


# ---------------------------------------------------------------------------------------------------------------------------

### Post By Claire Lueking

In [30]:
# Manually set public and private keys
n = 2537
e = 5
d = 1949

print(f"Public Key (n, e): ({n}, {e})")
print(f"Private Key (d): {d}")

Public Key (n, e): (2537, 5)
Private Key (d): 1949


In [31]:
# Decoding
cipher_text_str = "1248, 492, 1177, 2033, 70, 761, 2471, 70, 1718, 67, 353, 392, 70, 2214, 1177, 2478, 67, 392, 761, 2033, 2102, 70, 1281, 67, 67, 2025, 198"
# Convert the string to a list of integers
cipher_text = [int(num) for num in cipher_text_str.split(', ')]

decoded_message = Decode(n, d, cipher_text)
print(f"Decoded Message: {decoded_message}")

Decoded Message: What is your favorite book?


In [32]:
# Encoding a message
message_to_encode = "Harry Potter and the Goblet of Fire"
encoded_message = Encode(n, e, message_to_encode)

print(f"Message to Encode: {message_to_encode}")
print(f"Encoded Message: {encoded_message}")

Message to Encode: Harry Potter and the Goblet of Fire
Encoded Message: [1009, 1177, 392, 392, 1718, 70, 652, 67, 2033, 2033, 2102, 392, 70, 1177, 744, 969, 70, 2033, 492, 2102, 70, 1209, 67, 1281, 1716, 2102, 2033, 70, 67, 2214, 70, 925, 761, 392, 2102]


# ---------------------------------------------------------------------------------------------------------------------------

### 6. Write a Narrative (TWO pages of meaningful narrative about your process - not including the examples - about 800 words) here in this block.

* Describe your process. Did you plan ahead? Did you wing it? Do you wish you'd planned ahead more?

* Describe the results of exchanging keys and codes with classmates. Did it work the first time or did you need to make adjustments.Describe your process. Did you plan ahead? Did you wing it? Do you wish you'd planned ahead more?

* What was most challenging? 

* Who helped you with your project?  Which resources were most helpful?

* What was your Best Mistake? (funniest? most frustrating? the one you learned the most from?)




## Describe your process. Did you plan ahead? Did you wing it? Do you wish you'd planned ahead more?
    My process for completing this RSA project was to follow the provided instructions and implement the functions as dictated by the pseudo-code. 
    Each implementation of individual methods were not particularly difficult while working through them one by one, 
    but I also wanted to ensure they were working properly beforehand. Because of this, 
    I threw together a quick main function within each function to ensure the functions were performing properly. 
    While tedious, it gave me the confidence that my functions were returning the correct values. 
    Furthermore, I appreciated the clarity of the instructions provided for each of the functions since they provided a clear pseudo-code overview of what each function was required to return. 
    Since this is usually the way I complete most of the projects, I would say that my process was planned. 

## Describe the results of exchanging keys and codes with classmates. Did it work the first time or did you need to make adjustments. Describe your process. Did you plan ahead? Did you wing it? Do you wish you'd planned ahead more?
    I thought that exchanging the codes went well and I was quite surprised to see how fun it was to decode people’s messages with a program that I wrote. 
    The one troubling aspect to the code exchange was actually rewriting my encoding and decoding functions to take custom inputted public keys. 
    Since my input required inputting two prime numbers rather than the output of the public key and private key, 
    I had to find a way for my program to take the output values rather than prime numbers. 
    Once I got this area of the code working, it was quite easy to decipher the messages that I found in Piazza. 
    For this section especially, I wish I planned more ahead since I never even considered having to take in the keys rather than prime numbers. 
    For my process in this section, it was also quite simple. I would take the keys provided, input them into my private and public key function and then decode it. 
    From there, I would then encode a message in response to the question and post it on Piazza. 
    I ensured that the messages and responses are present and saved within my program to show the outputs. 

## What was most challenging?
    I think the most challenging part was the debugging for this project. 
    Honestly, my debugging skills are far from the greatest and finding the problems within my private and public key functions. 
    Within my private key function, I had to create a helper function, extended_gcd to help calculate the greatest common denominator within the function. 
    While this was annoying to implement and debug, it ultimately paid off since the function works properly. 
    Other than that, I think the only other annoying aspect of this project was figuring out how to take custom keys to decipher my classmates' messages which I talked about earlier. 

    
## Who helped you with your project? Which resources were most helpful?
    Overall, I completed the entire project on my own without the help from anyone. 
    The resources I used were online web pages for either python syntax or debugging assistance. 
    Along with this, rewatching a lot of lectures to understand both RSA and the Euclidean algorithm, especially Sriram’s video helped a lot in planning and understanding the formulas that needed to be implemented. 

## What was your Best Mistake? (funniest? most frustrating? the one you learned the most from?)
    My best mistake has to be implementing incorrect variables within my function which would return my public and private keys based on the inputted values. 
    Instead of using publickey[1] as an input, I was using privatekey[0] for the longest time and I could not understand why my encoding and decoding were messing up. 
    This was especially frustrating when I could decode a message, and I would encode a message in return which would then return back random symbols. 
    After a while I realized my mistake and went on to complete the function but still a silly mistake that I made. 


# ---------------------------------------------------------------------------------------------------------------------------

### 7. FME Exploration - (CODE INTERVIEW type question)



* Explain in detail why RSA needs to use an FME function and cannot just simply use the Python Mod function % .

* Provide some specific examples and/or include chart and graphs. 

* You may use your arguments/work from the Number Theory Mastery Workbook.




## Exploration
The security of RSA is based on the difficulty of factoring the product of two large prime numbers. 
The core operation in RSA involves exponentiation of integers modulo another integer. 
While the modulo operation is used in RSA, the need for an additional operation, the Fast Modular Exponentiation (FME) algorithm, 
arises due to efficiency and performance.
The basic modulo operation has a time complexity proportional to the size of the modulus. For large numbers, this can be computationally expensive.
The FME algorithm optimizes this process by breaking down the exponentiation into smaller, more manageable steps. 
It reduces the number of multiplications needed and significantly improves computational efficiency.

# ---------------------------------------------------------------------------------------------------------------------------

## CODE BREAKING ##

This section of the project is only available to students exchanging codes by the Friday (midnight) before the project is due.

After you have tested your RSA package yourself, and tested it with classmates by publishing both the private and public keys on Piazza, post 2 messages with just the public keys for people to break on the "Just Public Keys" thread - use both very small n ‘s (under 1000) for practice, and some with a challenge.


**Implementing a factoring algorithm:**

Begin by coding the basic brute force factorization algorithm given in pseudocode below.

Brute Force Factoring
<pre><code>def factorize(n):
    # n is a number, return the smallest factor of n
    for i from 2 to n-1:
        if i divides n:
            return i
        return FALSE
        </code></pre>


In [33]:
def factorize(n):
    # n is a number, return the smallest factor of n
    for i in range(2, n):
        if n % i == 0:
            return i
    return False

# ---------------------------------------------------------------------------------------------------------------------------

### 8. How to Break Code. 
* Explain in detail how breaking works in this text block. 
* What are the complete steps? What tools do you need?
* How secure is RSA? Why is it difficult to break codes in RSA? 
* Is our implementation of RSA secure? What are it's flaws?









### How to Break Code:

Breaking RSA involves factoring the modulus (n) into its prime factors (p and q). 
The modulus is a product of two large prime numbers, and finding these prime factors is computationally difficult, especially as the size of n increases.

The defactorization function broken down:
for i in range(2, n): This line starts a for loop that iterates over values of i from 2 to n - 1. It's checking potential factors starting from 2
    if n % i == 0: This line checks if i is a factor of n. The condition n % i == 0 checks if i evenly divides n
        return i: If a factor is found, the function immediately returns that factor (i). This is because the smallest factor is the one found first
return False: the loop completes without finding a factor, the function returns False, indicating that n is likely a prime number

Factorization algorithms: For small n, brute-force methods like the function above may work, but for larger n values, more sophisticated algorithms like Pollard's rho algorithm are needed.

RSA's security relies on the difficulty of factoring large numbers into their prime factors.
The security increases with longer key lengths, making it computationally infeasible to factorize the modulus.
The security of RSA is based on the lack of an efficient algorithm for factoring large semiprime numbers.

The provided RSA implementation in the project is a pretty basic version of RSA. Its security depends on the size of the keys used.
A flaw could be the use of small key sizes, which may be susceptible to attacks using more advanced factorization methods.
The key generation process might be better implemented by including checks for prime numbers, ensuring the selected primes are indeed prime.

# ---------------------------------------------------------------------------------------------------------------------------

### 9. Decode!  Use a mix of text and code blocks

* Decode one example from Piazza in detial showing all the steps.
* Decode and Respond to 3 "just codes with public keys" in Piazza with different sizes of n. Include complete results here.
* What did you notice about larger n s?


# What did you notice about larger n s?
I understand the larger n's require a longer period of time code break using the factorize function, however I believe that the values
from the forum posts I responded to did not drastically increase runtime. It was hard to notice a difference. 

# Breaking Professor Stade's Message:
### The message: The Conquistador's treasure is buried south of Creed.
### Response: If only I could understand the map...

In [34]:
# Given public key
public_key = (703, 113)  # Replace this with the public key we want to break

# Extract the modulus 'n'
n = public_key[0]

# Use the factorize function to find a factor of 'n'
factor = factorize(n)

if factor:
    print(f"p: {factor}")
    # Use the factor to calculate the other factor and break the key
    other_factor = n // factor
    print(f"q: {other_factor}")
else:
    print("Unable to find a factor.")

p: 19
q: 37


In [35]:
# Generate keys

# The Find_Public_Key_e function is used to generate the public key, and the Find_Private_Key_d function is used to generate the private key.
p = 19
q = 37
public_key = Find_Public_Key_e(p, q)
private_key = Find_Private_Key_d(public_key[1], p, q)

print(f"Prime Numbers: p = {p}, q = {q}")
print(f"Public Key (n, e): {public_key}")
print(f"Private Key (d): {private_key}")

Prime Numbers: p = 19, q = 37
Public Key (n, e): (703, 5)
Private Key (d): 389


In [36]:
# Decoding
# We use the Public Key and Private Key "n" values as inputs
cipher_text_str = "544, 472, 233, 242, 250, 555, 591, 550, 376, 364, 210, 165, 526, 47, 555, 95, 476, 210, 242, 165, 95, 233, 526, 210, 376, 95, 233, 242, 364, 210, 242, 224, 376, 95, 364, 233, 47, 242, 210, 555, 376, 165, 472, 242, 555, 410, 242, 250, 95, 233, 233, 47, 145"
# Convert the string to a list of integers
cipher_text = [int(num) for num in cipher_text_str.split(', ')]

decoded_message = Decode(public_key[0], private_key, cipher_text)
print(f"Decoded Message: {decoded_message}")

Decoded Message: The Conquistador's treasure is buried south of Creed.


In [37]:
# Encoding a message
message_to_encode = "If only I could understand the map..."
encoded_message = Encode(public_key[0], public_key[1], message_to_encode)

print(f"Message to Encode: {message_to_encode}")
print(f"Encoded Message: {encoded_message}")

Message to Encode: If only I could understand the map...
Encoded Message: [517, 410, 242, 555, 591, 90, 581, 242, 517, 242, 511, 555, 376, 90, 47, 242, 376, 591, 47, 233, 95, 210, 165, 526, 591, 47, 242, 165, 472, 233, 242, 523, 526, 519, 145, 145, 145]


# ---------------------------------------------------------------------------------------------------------------------------

# Breaking James Keller's Code
### The Message: Keep Clam and Code On
### Response: Wise words to live by!

In [38]:
# Given public key
public_key = (8633, 5)  # Replace this with the public key we want to break

# Extract the modulus 'n'
n = public_key[0]

# Use the factorize function to find a factor of 'n'
factor = factorize(n)

if factor:
    print(f"p: {factor}")
    # Use the factor to calculate the other factor and break the key
    other_factor = n // factor
    print(f"q: {other_factor}")
else:
    print("Unable to find a factor.")

p: 89
q: 97


In [39]:
# Generate keys

# The Find_Public_Key_e function is used to generate the public key, and the Find_Private_Key_d function is used to generate the private key.
p = 89
q = 97
public_key = Find_Public_Key_e(p, q)
private_key = Find_Private_Key_d(public_key[1], p, q)

print(f"Prime Numbers: p = {p}, q = {q}")
print(f"Public Key (n, e): {public_key}")
print(f"Private Key (d): {private_key}")

Prime Numbers: p = 89, q = 97
Public Key (n, e): (8633, 5)
Private Key (d): 5069


In [40]:
# Decoding
# We use the Public Key and Private Key "n" values as inputs
cipher_text_str = "7835, 1412, 1412, 1999, 6594, 1604, 1098, 194, 6235, 6594, 194, 5409, 7615, 6594, 1604, 1511, 7615, 1412, 6594, 4842, 5409"
# Convert the string to a list of integers
cipher_text = [int(num) for num in cipher_text_str.split(', ')]

decoded_message = Decode(public_key[0], private_key, cipher_text)
print(f"Decoded Message: {decoded_message}")

Decoded Message: Keep Clam and Code On


In [41]:
# Encoding a message
message_to_encode = "Wise words to live by!"
encoded_message = Encode(public_key[0], public_key[1], message_to_encode)

print(f"Message to Encode: {message_to_encode}")
print(f"Encoded Message: {encoded_message}")

Message to Encode: Wise words to live by!
Encoded Message: [7088, 4250, 2724, 1412, 6594, 8073, 1511, 456, 7615, 2724, 6594, 950, 1511, 6594, 1098, 4250, 6706, 1412, 6594, 8052, 7751, 2004]


# ---------------------------------------------------------------------------------------------------------------------------

# Breaking Ebrahim Azarisooreh's Code
### The Message: The answer to life, the universe, and everything is: 42.
### Response: Who knew the meaning of everything could be a two-digit number? Time to rethink those existential crises!

In [42]:
# Given public key
public_key = (44243, 7)  # Replace this with the public key we want to break

# Extract the modulus 'n'
n = public_key[0]

# Use the factorize function to find a factor of 'n'
factor = factorize(n)

if factor:
    print(f"p: {factor}")
    # Use the factor to calculate the other factor and break the key
    other_factor = n // factor
    print(f"q: {other_factor}")
else:
    print("Unable to find a factor.")

p: 151
q: 293


In [43]:
# Generate keys

# The Find_Public_Key_e function is used to generate the public key, and the Find_Private_Key_d function is used to generate the private key.
p = 151
q = 293
public_key = Find_Public_Key_e(p, q)
private_key = Find_Private_Key_d(public_key[1], p, q)

print(f"Prime Numbers: p = {p}, q = {q}")
print(f"Public Key (n, e): {public_key}")
print(f"Private Key (d): {private_key}")

Prime Numbers: p = 151, q = 293
Public Key (n, e): (44243, 7)
Private Key (d): 37543


In [44]:
# Decoding
# We use the Public Key and Private Key "n" values as inputs
cipher_text_str = "2694, 14335, 23616, 5166, 10909, 11297, 10095, 16427, 23616, 13887, 5166, 37331, 3687, 5166, 29541, 22886, 30381, 23616, 14127, 5166, 37331, 14335, 23616, 5166, 20850, 11297, 22886, 38925, 23616, 13887, 10095, 23616, 14127, 5166, 10909, 11297, 20406, 5166, 23616, 38925, 23616, 13887, 14634, 37331, 14335, 22886, 11297, 40714, 5166, 22886, 10095, 44189, 5166, 31566, 27120, 39024"
# Convert the string to a list of integers
cipher_text = [int(num) for num in cipher_text_str.split(', ')]

decoded_message = Decode(public_key[0], private_key, cipher_text)
print(f"Decoded Message: {decoded_message}")

Decoded Message: The answer to life, the universe, and everything is: 42.


In [45]:
# Encoding a message
message_to_encode = "Who knew the meaning of everything could be a two-digit number? Time to rethink those existential crises!"
encoded_message = Encode(public_key[0], public_key[1], message_to_encode)

print(f"Message to Encode: {message_to_encode}")
print(f"Encoded Message: {encoded_message}")

Message to Encode: Who knew the meaning of everything could be a two-digit number? Time to rethink those existential crises!
Encoded Message: [12212, 14335, 3687, 5166, 12751, 11297, 23616, 16427, 5166, 37331, 14335, 23616, 5166, 21244, 23616, 10909, 11297, 22886, 11297, 40714, 5166, 3687, 30381, 5166, 23616, 38925, 23616, 13887, 14634, 37331, 14335, 22886, 11297, 40714, 5166, 32609, 3687, 20850, 29541, 20406, 5166, 25756, 23616, 5166, 10909, 5166, 37331, 16427, 3687, 21276, 20406, 22886, 40714, 22886, 37331, 5166, 11297, 20850, 21244, 25756, 23616, 13887, 24582, 5166, 2694, 22886, 21244, 23616, 5166, 37331, 3687, 5166, 13887, 23616, 37331, 14335, 22886, 11297, 12751, 5166, 37331, 14335, 3687, 10095, 23616, 5166, 23616, 8085, 22886, 10095, 37331, 23616, 11297, 37331, 22886, 10909, 29541, 5166, 32609, 13887, 22886, 10095, 23616, 10095, 1694]


# ---------------------------------------------------------------------------------------------------------------------------

# My own forum post
### Message: I still can't believe it's not butter
### Encoded Message: [6033, 7329, 58337, 21990, 64362, 65098, 65098, 7329, 75756, 8916, 101757, 72851, 21990, 7329, 81277, 94328, 65098, 64362, 94328, 11237, 94328, 7329, 64362, 21990, 72851, 58337, 7329, 101757, 69050, 21990, 7329, 81277, 46423, 21990, 21990, 94328, 82061]

### Public Key: 103861, 5

In [46]:
# Generate keys

# The Find_Public_Key_e function is used to generate the public key, and the Find_Private_Key_d function is used to generate the private key.
p = 283
q = 367
public_key = Find_Public_Key_e(p, q)
private_key = Find_Private_Key_d(public_key[1], p, q)

print(f"Prime Numbers: p = {p}, q = {q}")
print(f"Public Key (n, e): {public_key}")
print(f"Private Key (d): {private_key}")

Prime Numbers: p = 283, q = 367
Public Key (n, e): (103861, 5)
Private Key (d): 41285


In [47]:
# Encoding a message
message_to_encode = "I still can't believe it's not butter"
encoded_message = Encode(public_key[0], public_key[1], message_to_encode)

print(f"Message to Encode: {message_to_encode}")
print(f"Encoded Message: {encoded_message}")

Message to Encode: I still can't believe it's not butter
Encoded Message: [6033, 7329, 58337, 21990, 64362, 65098, 65098, 7329, 75756, 8916, 101757, 72851, 21990, 7329, 81277, 94328, 65098, 64362, 94328, 11237, 94328, 7329, 64362, 21990, 72851, 58337, 7329, 101757, 69050, 21990, 7329, 81277, 46423, 21990, 21990, 94328, 82061]


In [48]:
# Decoding
# We use the Public Key and Private Key "n" values as inputs
cipher_text_str = "6033, 7329, 58337, 21990, 64362, 65098, 65098, 7329, 75756, 8916, 101757, 72851, 21990, 7329, 81277, 94328, 65098, 64362, 94328, 11237, 94328, 7329, 64362, 21990, 72851, 58337, 7329, 101757, 69050, 21990, 7329, 81277, 46423, 21990, 21990, 94328, 82061"
# Convert the string to a list of integers
cipher_text = [int(num) for num in cipher_text_str.split(', ')]

decoded_message = Decode(public_key[0], private_key, cipher_text)
print(f"Decoded Message: {decoded_message}")

Decoded Message: I still can't believe it's not butter


# ---------------------------------------------------------------------------------------------------------------------------


### 10. Custom CODE Feature ##
The custom feature should be a "Stand Alone" feature at the end of the notebook. If you want to use code from above, please copy the functions again as part of your feature so it can be tested independently. Be sure to provide a demonstration showing that it works. See RSA Guide for more information and suggestions. 

**Do not forget the self-grading element.**


### This block was only used to help find the value to factor. This requires the functions from above to run, but not necessary to test. 

In [49]:
# Generate keys

# The Find_Public_Key_e function is used to generate the public key, and the Find_Private_Key_d function is used to generate the private key.
p = 240279349
q = 240283567
public_key = Find_Public_Key_e(p, q)
private_key = Find_Private_Key_d(public_key[1], p, q)

print(f"Prime Numbers: p = {p}, q = {q}")
print(f"Public Key (n, e): {public_key}")
print(f"Private Key (d): {private_key}")

Prime Numbers: p = 240279349, q = 240283567
Public Key (n, e): (57735179054157883, 5)
Private Key (d): 34641107144156981


# ---------------------------------------------------------------------------------------------------------------------------

# Summary

Custom CODE Feature Overview

The custom code feature compares the three factorization techniques: Brute-Force Factorization, Pollard's Rho Factorization, and Fermat Factorization.
The runtimes were found by using %%time which shows the computational time to complete the factorization.

    Brute-Force Factorization:
        This method uses a straightforward brute-force approach by iterating through numbers from 2 to n−1 to find the smallest factor.
        Time Complexity: O(n)
        The provided example shows a wall time of 20.6 seconds, highlighting its inefficiency for larger inputs.

    Pollard's Rho Factorization:
        Pollard's Rho is a probabilistic algorithm with better average-case runtime compared to brute-force.
        It relies on randomization and a constant function f(x)=(x2+1)modn.
        The example demonstrates a factorization in 35.4 milliseconds, showcasing its efficiency for the given large number.

    Fermat Factorization:
        Fermat's method aims to express n as the difference of two squares: n=a^2−b^2.
        It is particularly efficient for large odd composite numbers.
        The example shows a fast runtime of 95.8 µs due to its targeted approach.

# ---------------------------------------------------------------------------------------------------------------------------

# Our Brute-Force Factorize Function

In [50]:
%%time
def factorize(n):
    # n is a number, return the smallest factor of n
    for i in range(2, n):
        if n % i == 0:
            return i
    return False

#Test Usage
large_number = 57735179054157883
result = factorize(large_number)
print(f"A factor of {large_number} found using our factorize function: {result}")

A factor of 57735179054157883 found using our factorize function: 240279349
CPU times: user 20.6 s, sys: 0 ns, total: 20.6 s
Wall time: 20.6 s


## Brute-Force Factorize Explanation:
The function provided by the example represents a basic brute-force factorization method. It aims to find the smallest factor of a given number n by iterating through all numbers from 2 to n-1.
The time complexity of this method is linear (O(n)) since it iterates through each number up to n-1 until it finds a factor.
The function uses a simple for loop that starts from 2 and checks if each number divides n. The first factor found is immediately returned.
The inefficiency becomes apparent for large numbers, as the linear search through factors becomes extremely time consuming. The wall time of 20.6 seconds highlights the impracticality of brute-force factorization for larger inputs, which will only drastically increase as the value gets larger.
This brute-force method serves as a baseline function for factorization but is not suitable for largeer scale factorization due to its inefficiency when values become larger.

# ---------------------------------------------------------------------------------------------------------------------------

# Pollard's Rho Factorization Function

In [51]:
%%time
import random

def pollards_rho(n, max_iterations=100000000):
    # Helper function to calculate the greatest common divisor
    def gcd(a, b):
        while b:
            a, b = b, a % b
        return a

    # Initialize random starting points and a constant function
    x = random.randint(1, n - 1)
    y = x
    d = 1

    # Define the function f(x) used in the algorithm
    f = lambda x: (x**2 + 1) % n

    # Main loop of Pollard's Rho algorithm
    for _ in range(max_iterations):
        x = f(x)
        y = f(f(y))
        d = gcd(abs(x - y), n)

        # If a non-trivial factor is found, return it
        if d > 1:
            return d
    
    # If no factor is found within the specified iterations, return None
    return None

# Test usage
large_number = 57735179054157883
result = pollards_rho(large_number)
print(f"A factor of {large_number} found using Pollard's Rho: {result}")

A factor of 57735179054157883 found using Pollard's Rho: 240279349
CPU times: user 37.5 ms, sys: 0 ns, total: 37.5 ms
Wall time: 35.4 ms


# Pollard's Rho Explanation
Pollard's Rho is a probabilistic algorithm that uses randomization. It has a better average-case runtime compared to the brute-force method. Its runtime depends on the number of iterations and the nature of the input. For the given large number, it finds a factor much faster due to its efficient probabilistic approach.

Pollard's Rho relies on randomization, initializing random starting points (x and y) and a constant function f(x). This introduces a level of unpredictability into the algorithm.
The function f(x) is defined as (x**2 + 1) % n. This function, based on modular arithmetic, is at the core of Pollard's Rho and contributes to its efficiency.
The algorithm iterates through the main loop a specified number of times (max_iterations). In each iteration, it updates the values of x and y using the function f(x).
At each iteration, the algorithm calculates the greatest common divisor (GCD) of abs(x - y) and n. If a non-trivial factor is found (GCD > 1), it is returned immediately.
If no factor is found within the specified iterations, the function returns None.

### Runtime Analysis
Pollard's Rho has a better average-case runtime compared to the brute-force method, especially for large numbers
The runtime depends on the number of iterations (max_iterations). Increasing the number of iterations may increase the likelihood of finding a factor but will also increase the runtime. Larger numbers such as the example value provided require a significant increase in iterations in order to find the factor. 

# ----------------------------------------------------------------------------------------------------

# Fermat Factorization Function

In [52]:
%%time
import math

def fermat_factorization(n):
    # Check if n is even
    if n % 2 == 0:
        return 2, n // 2
    
    # Express n as the difference of two squares: n = a^2 - b^2
    a = math.isqrt(n) + 1  # Initial guess, rounded up to the nearest integer
    b2 = a**2 - n
    
    # Adjust initial guess if b^2 is negative
    while b2 < 0:
        a += 1
        b2 = a**2 - n
    
    # Keep incrementing a until b^2 is a perfect square
    while not math.isqrt(b2)**2 == b2:
        a += 1
        b2 = a**2 - n
    
    # Calculate the factors
    b = math.isqrt(b2)
    return a + b, a - b

# Test usage:
large_number = 57735179054157883
factors = fermat_factorization(large_number)
print(f"Factors of {large_number} using Fermat's factorization: {factors}")

Factors of 57735179054157883 using Fermat's factorization: (240283567, 240279349)
CPU times: user 102 µs, sys: 0 ns, total: 102 µs
Wall time: 95.8 µs


# Fermat Factorization Explained:

The Fermat Factorization method is employed to find the factors of a given odd number n. If n is even, it returns the factors immediately. This is because if n is not odd, it would have at least one factor of 2. In thiscase, Fermat's method can immediately return the factors 2 and n//2 without going through the process of expressing n as the difference of two squares. An initial guess for a is made by rounding up the square root of n. If b^2 is initially negative, a is adjusted until a non-negative value is obtained. The function then iteratively increments a until b^2 is a perfect square. The factors are then calculated based on the final values of a and b.

### Runtime Analysis
The runtime of the function is extremely fast, as seen in the provided test case with a wall time of 95.8 µs. This is due to the efficient nature of Fermat's factorization method for the given input. While in our provided example the runtime was significantly faster than Pollard's Rho factorization algorithm, this method may not be as effective for very large numbers or composite numbers with specific properties in direct comparison to Pollard's Rho. 


# ----------------------------------------------------------------------------------------------------

**Please use the grading guide below to self grade your Custom Feature.**

GRADING FOR CUSTOM FEATURE:

15 pts  Wow.  It is amazing.
        Shows initiative and originality. 
        You did something extra special and pushed yourself.
        You went beyond all expectations 
        You broke the rules in a creative way. 
        Your coding and commenting is exceptional.
        Excellent 

10 - 14 points - It is GOOD! 
        You were a “self starter.” 
         You did everything  requested. 
        All expectations met. 
       	You did a very good job. 
        Good use of commenting.
        Shows mastery of skills.

5 -10 points  - Okay.
        Minimum requirements.
        Commenting weak.

0 -5 points - It is not finished. 
          Does meet objectives. 
            Did not follow directions. 
            Chose not to do this part (which is a totally fine choice)


## Self grading of custom feature ##

Here in this block, please rate what score out of 15 your custom feature merits given the criteria above:

* For example, if you are brand new to programming, using a main function could be an amazing feature - tell me how this helped you move to a new level.
* In what ways did you push yourself? Did you try something you've never done before?
* Alternatively, if you just did not have the time to do the custum feature, that is actually just fine and a reasonable choice for an adult. No judgment.

# Self Assessment
### 14 Points
For my addition to this programming assignment, I decided to further improve the factorization function. First, I determined why the basic factorization function was inefficient and from there, researched various algorithms which would be more efficient. From this point, I determined that the two factorization techniques, Pollard's Rho and Fermat's factorization algorithms were both significantly more efficient than the default factorization function provided, but also were more efficient with varying inputs. 

Through this section, I pushed myself to understand and develop code which stayed true to the original Pollard's Rho and Fermat factorization algorithms while also understanding why they are more efficient than the basic factorization function. While I am proud of my accomplishments, they were definitely not the hardest coding assignments I've done and the majority of the time was understanding how the functions operated rather than coding. I believe that my code shows clean commenting which helps the reader understand what each part of the function is doing and efficient solutions within the functions. 